<a href="https://colab.research.google.com/github/jesusoviedo/AI-For-Beginners/blob/main/Semana_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**SEMANA 1**

Importamos las librerías:

In [ ]:
## Para datos
import pandas as pd
import numpy as np
## Para gráficos
import matplotlib.pyplot as plt


Abrimos el data-set como un dataframe: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

In [ ]:
dtf = pd.read_csv('/content/titanic.csv', sep='\t')

# **Exploración de datos**

Visualizamos el conjunto de datos: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html

In [ ]:
dtf.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

Vemos tamaño del conjunto de datos: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html

In [ ]:
print(dtf.shape)

(887, 8)


Vemos los nombres de los atributos a través de la lista retornada por .columns

In [ ]:
print(dtf.columns)

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard',
       'Parents/Children Aboard', 'Fare'],
      dtype='object')


Vemos información general https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html

In [ ]:
print(dtf.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Survived                 887 non-null    int64  
 1   Pclass                   887 non-null    int64  
 2   Name                     887 non-null    object 
 3   Sex                      887 non-null    object 
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64  
 6   Parents/Children Aboard  887 non-null    int64  
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB
None


Vemos las estadísticas de los atributos numéricos: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html

In [ ]:
dtf.describe()

Survived      Pclass         Age  Siblings/Spouses Aboard  \
count  887.000000  887.000000  887.000000               887.000000   
mean     0.385569    2.305524   29.471443                 0.525366   
std      0.487004    0.836662   14.121908                 1.104669   
min      0.000000    1.000000    0.420000                 0.000000   
25%      0.000000    2.000000   20.250000                 0.000000   
50%      0.000000    3.000000   28.000000                 0.000000   
75%      1.000000    3.000000   38.000000                 1.000000   
max      1.000000    3.000000   80.000000                 8.000000   

       Parents/Children Aboard       Fare  
count               887.000000  887.00000  
mean                  0.383315   32.30542  
std                   0.807466   49.78204  
min                   0.000000    0.00000  
25%                   0.000000    7.92500  
50%                   0.000000   14.45420  
75%                   0.000000   31.13750  
max                   6.000000  512.32920

Vemos estadísticas de atributos categóricos.

In [ ]:
dtf.describe(include=["object", "bool"])

Name   Sex
count                      887   887
unique                     887     2
top     Mr. Owen Harris Braund  male
freq                         1   573

Vemos frecuencias de atributos individuales: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html



In [ ]:
dtf["Pclass"].value_counts()

3    487
1    216
2    184
Name: Pclass, dtype: int64

In [ ]:
dtf["Sex"].value_counts()

male      573
female    314
Name: Sex, dtype: int64

Encontrar valores nulos: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html

In [ ]:
dtfn=dtf.isna()
dtfn.describe()

Survived Pclass   Name    Sex    Age Siblings/Spouses Aboard  \
count       887    887    887    887    887                     887   
unique        1      1      1      1      1                       1   
top       False  False  False  False  False                   False   
freq        887    887    887    887    887                     887   

       Parents/Children Aboard   Fare  
count                      887    887  
unique                       1      1  
top                      False  False  
freq                       887    887

In [ ]:
dtfn.head()

Survived  Pclass   Name    Sex    Age  Siblings/Spouses Aboard  \
0     False   False  False  False  False                    False   
1     False   False  False  False  False                    False   
2     False   False  False  False  False                    False   
3     False   False  False  False  False                    False   
4     False   False  False  False  False                    False   

   Parents/Children Aboard   Fare  
0                    False  False  
1                    False  False  
2                    False  False  
3                    False  False  
4                    False  False

# **Preprocesamiento**

Eliminar instancias con valores perdidos: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

In [ ]:
dtf.dropna()

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

Asignar valor a datos faltantes: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html

In [ ]:
dtf["Age"].fillna(dtf["Age"].mean())
dtf

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

Codificación numérica de variables binarias: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.replace.html



In [ ]:
lista = {"Sex": {"male": 0, "female": 1}}
dtf =  dtf.replace(lista)
dtf.head()

Survived  Pclass                                               Name  Sex  \
0         0       3                             Mr. Owen Harris Braund    0   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...    1   
2         1       3                              Miss. Laina Heikkinen    1   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle    1   
4         0       3                            Mr. William Henry Allen    0   

    Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0  22.0                        1                        0   7.2500  
1  38.0                        1                        0  71.2833  
2  26.0                        0                        0   7.9250  
3  35.0                        1                        0  53.1000  
4  35.0                        0                        0   8.0500

Vemos de vuelta en que clase de atributo se transformó "Sex".

In [ ]:
dtf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Survived                 887 non-null    int64  
 1   Pclass                   887 non-null    int64  
 2   Name                     887 non-null    object 
 3   Sex                      887 non-null    int64  
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64  
 6   Parents/Children Aboard  887 non-null    int64  
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(5), object(1)
memory usage: 55.6+ KB


Eliminamos el atributo "Name": https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html

In [ ]:
dtf=dtf.drop(['Name'], axis=1)
dtf.head()

Survived  Pclass  Sex   Age  Siblings/Spouses Aboard  \
0         0       3    0  22.0                        1   
1         1       1    1  38.0                        1   
2         1       3    1  26.0                        0   
3         1       1    1  35.0                        1   
4         0       3    0  35.0                        0   

   Parents/Children Aboard     Fare  
0                        0   7.2500  
1                        0  71.2833  
2                        0   7.9250  
3                        0  53.1000  
4                        0   8.0500

Aplicamos normalización de atributos.

In [ ]:
dtf_n=(dtf['Age']-dtf['Age'].min())/(dtf['Age'].max()-dtf['Age'].min())
dtf_n.head()

0    0.271174
1    0.472229
2    0.321438
3    0.434531
4    0.434531
Name: Age, dtype: float64

Supongamos que solo queremos normalizar el atributo age.

In [ ]:
dtf['Age']=dtf_n
dtf.head()

Survived  Pclass  Sex       Age  Siblings/Spouses Aboard  \
0         0       3    0  0.271174                        1   
1         1       1    1  0.472229                        1   
2         1       3    1  0.321438                        0   
3         1       1    1  0.434531                        1   
4         0       3    0  0.434531                        0   

   Parents/Children Aboard     Fare  
0                        0   7.2500  
1                        0  71.2833  
2                        0   7.9250  
3                        0  53.1000  
4                        0   8.0500

# **Organización de datos**

Aplicar partición de entrenamiento 70% y prueba 30%.

In [ ]:
from sklearn import model_selection
from sklearn.model_selection import train_test_split

dtf_train, dtf_test = model_selection.train_test_split(dtf,
                      test_size=0.3, random_state=7)

Dividir atributos de las etiquetas seleccionando atributos.

In [ ]:
atributos = ['Pclass', 'Age']
etiqueta = ['Survived']
X_train = dtf_train[atributos].values # Atributos
y_train = dtf_train[etiqueta].values # Etiqueta
X_test = dtf_test[atributos].values # Atributos
y_test = dtf_test[etiqueta].values # Etiqueta

Dividir atributos de las etiquetas usando todos los atributos: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html

In [ ]:
etiqueta = ['Survived']
X_train = dtf_train.drop(['Survived'], axis=1) # Atributos
y_train = dtf_train[etiqueta]# Etiqueta
X_test = dtf_test.drop(['Survived'], axis=1) # Atributos
y_test = dtf_test[etiqueta]# Etiqueta
y_test

Survived
387         1
783         0
804         0
299         1
171         1
..        ...
239         0
806         0
422         0
192         1
191         1

[267 rows x 1 columns]

# Aplicación de modelos

## Modelo 1: Regresión logística

Entrenamos un modelo de regresión logística y predecimos etiquetas: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html



In [ ]:
from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression()
logistic_classifier.fit(X_train, y_train.values.ravel())

LogisticRegression()

Realizamos la predicción

In [ ]:
y_pred = logistic_classifier.predict(X_test)

Obtenemos la matriz de confusión: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))

[[136  19]
 [ 34  78]]


Obtenemos una tabla de métricas: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84       155
           1       0.80      0.70      0.75       112

    accuracy                           0.80       267
   macro avg       0.80      0.79      0.79       267
weighted avg       0.80      0.80      0.80       267



##Modelo 2: Árbol de decisión

Entrenamos un árbol de decisión y predecimos etiquetas: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html


In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

Realizamos la predicción

In [ ]:
y_pred = clf.predict(X_test)

Obtenemos la matriz de confusión: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[127  28]
 [ 34  78]]


Obtenemos una tabla de métricas:

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html

http://iamirmasoud.com/2022/06/19/understanding-micro-macro-and-weighted-averages-for-scikit-learn-metrics-in-multi-class-classification-with-example/


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.82      0.80       155
           1       0.74      0.70      0.72       112

    accuracy                           0.77       267
   macro avg       0.76      0.76      0.76       267
weighted avg       0.77      0.77      0.77       267



Visualizar el arbol:
https://scikit-learn.org/stable/modules/generated/sklearn.tree.export_graphviz.html



In [ ]:
import graphviz
from sklearn import tree

dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=X_train.columns,
                                class_names=['No Survived', 'Survived'],
                                filled=True, rounded=True,
                                special_characters=True)

graph = graphviz.Source(dot_data)
graph.view()

'Source.gv.pdf'

##Modelo 3: Support Vector Machine

Entrenamos un modelo SVM y predecimos etiquetas: http://scikit-learn.org/stable/modules/svm.html

In [ ]:
from sklearn import svm

clf = svm.SVC(kernel='linear')

clf.fit(X_train, y_train.values.ravel())


SVC(kernel='linear')

Realizamos la predicción

In [ ]:
y_pred = clf.predict(X_test)

Obtenemos la matriz de confusión

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[134  21]
 [ 31  81]]


Obtenemos una tabla de métricas

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.86      0.84       155
           1       0.79      0.72      0.76       112

    accuracy                           0.81       267
   macro avg       0.80      0.79      0.80       267
weighted avg       0.80      0.81      0.80       267



##Modelo 4: KNN

Entrenamos un modelo KNN y predecimos etiquetas: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train.values.ravel())

KNeighborsClassifier(n_neighbors=3)

Realizamos la predicción

In [ ]:
y_pred = knn.predict(X_test)

Obtenemos la matriz de confusión

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[131  24]
 [ 37  75]]


Obtenemos una tabla de métricas

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.85      0.81       155
           1       0.76      0.67      0.71       112

    accuracy                           0.77       267
   macro avg       0.77      0.76      0.76       267
weighted avg       0.77      0.77      0.77       267



### TAREA NO CALIFICADA
Aplicar el clasificador Random Forest:
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier